Imports e Funções

In [1]:
import pandas as pd

def estruturar(a):
    #a = nome da base
    #dividir colunas
    i= [0,2,10,12,24,27,39,49,52,56,69,82,95,108,121,134,147,152,170,188,201,202,210,217,230,242,245]
    x=0
    y=1

    while x<len(i)-1:
        if y ==1:
            a[y]=a[0].str.slice(stop=i[y])
            #print(y)
            x+=1
            y+=1
        elif y==26:
            a[y]=a[0].str.slice(start=i[x])
            #print(y)
            x+=1
            y+=1
        else:
            a[y]=a[0].str.slice(start=i[x],stop=i[y])
            #print(y)
            x+=1
            y+=1
            if x==28:
                break
    a = a.drop(a.index[0])
    #renomear colunas, para mis detalhes ver arquivo Desccol.txt
    a.columns = ['0','TIPREG','DATA DO PREGÃO','CODBDI','CODNEG','TPMERC','NOMRES','ESPECI','MODREF','PRAZOT','PREABE','PREMAX','PREMIN','PREMED','PREULT','PREOFC','PREOFV','TOTNEG','QUATOT','VOLTOT','PREEXE','INDOPC','DATVEN','FATCOT','PTOEXE','CODISI','DISMES']
    print(len(a),'OK',)
    return a

def filtrar(a):
    #a = nome da base
    print('filtro de TIPREG')
    
    print(len(a))
    a.columns = ['TIPREG','DATA DO PREGÃO','CODBDI','CODNEG','TPMERC','NOMRES','ESPECI','MODREF','PRAZOT','PREABE','PREMAX','PREMIN','PREMED','PREULT','PREOFC','PREOFV','TOTNEG','QUATOT','VOLTOT','PREEXE','INDOPC','DATVEN','FATCOT','PTOEXE','CODISI','DISMES']
    a = a.convert_dtypes()
    a['TIPREG']= pd.to_numeric(a['TIPREG'])
    datamask=a['TIPREG']==1
    a=a[datamask]
    print(len(a))
    
    print('filtro de ESPECI')
    exc=["CI        ", "CI      MB", "CI  ER    ", "CI  ER  MB", "CI *      ", "DIR ORD NM", "DIR PRE N2", "DR3       ", "DRN       ", "DRN A     ", "DRN C     " , "DRN ED    "]
    a=a[~a.ESPECI.isin(exc)]
    print(len(a))
    return a

Preparação das tabelas

In [2]:
#bases de dados obtidas diretamente do site da B3

##Importação das bases de dados

data2018 = pd.read_csv('COTAHIST_A2018.TXT', header=None)
data2018 = data2018.drop(data2018.index[0])
estruturar(data2018)

data2019 = pd.read_csv('COTAHIST_A2019.TXT', header=None)
data2019 = data2019.drop(data2019.index[0])
estruturar(data2019)

data2020 = pd.read_csv('COTAHIST_A2020.TXT', header=None)
data2020 = data2020.drop(data2020.index[0])
estruturar(data2020)

data2021 = pd.read_csv('COTAHIST_A2021.TXT', header=None)
data2021 = data2021.drop(data2021.index[0])
estruturar(data2021)

data2022 = pd.read_csv('COTAHIST_A2022.TXT', header=None)
data2022 = data2022.drop(data2022.index[0])
estruturar(data2022)

580155 OK
779229 OK
1251646 OK
1831862 OK
1472916 OK

,0,TIPREG,DATA DO PREGÃO,CODBDI,CODNEG,TPMERC,NOMRES,ESPECI,MODREF,PRAZOT,...,TOTNEG,QUATOT,VOLTOT,PREEXE,INDOPC,DATVEN,FATCOT,PTOEXE,CODISI,DISMES
2,012022010302A1BB34 010ABB LTD DRN ...,01,20220103,02,A1BB34,010,ABB LTD,DRN,,R$,...,00008,000000000000000192,000000000001042902,0000000000000,0,99991231,0000001,0000000000000,BRA1BBBDR009,101
3,012022010302A1CR34 010AMCOR PLC DRN ...,01,20220103,02,A1CR34,010,AMCOR PLC,DRN,,R$,...,00001,000000000000000002,000000000000013380,0000000000000,0,99991231,0000001,0000000000000,BRA1CRBDR003,105
4,012022010302A1DI34 010ANALOG DEVICDRN ...,01,20220103,02,A1DI34,010,ANALOG DEVIC,DRN,,R$,...,00003,000000000000000078,000000000003892051,0000000000000,0,99991231,0000001,0000000000000,BRA1DIBDR000,108
5,012022010302A1DM34 010ARCHER DANIEDRN ...,01,20220103,02,A1DM34,010,ARCHER DANIE,DRN,,R$,...,00002,000000000000000022,000000000000847260,0000000000000,0,99991231,0000001,0000000000000,BRA1DMBDR002,108
6,012022010302A1FL34 010AFLAC INC DRN ...,01,20220103,02,A1FL34,010,AFLAC INC,DRN,,R$,...,00001,000000000000000001,000000000000031936,0000000000000,0,99991231,0000001,0000000000000,BRA1FLBDR009,108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1472913,012022091382USIMV707 080USIME PNA ...,01,20220913,82,USIMV707,080,USIME,PNA N1,000,R$,...,00028,000000000000094100,000000000001426800,0000000000707,0,20221021,0000001,0000000000000,BRUSIMACNPA6,167
1472914,012022091482USIMV707 080USIME PNA ...,01,20220914,82,USIMV707,080,USIME,PNA N1,000,R$,...,00038,000000000000062600,000000000001201100,0000000000707,0,20221021,0000001,0000000000000,BRUSIMACNPA6,167
1472915,012022080382USIMV727 080USIME PNA ...,01,20220803,82,USIMV727,080,USIME,PNA N1,000,R$,...,00001,000000000000000100,000000000000002000,0000000000727,0,20221021,0000001,0000000000000,BRUSIMACNPA6,167
1472916,012022081682USIMV727 080USIME PNA ...,01,20220816,82,USIMV727,080,USIME,PNA N1,000,R$,...,00001,000000000000001000,000000000000018000,0000000000727,0,20221021,0000001,0000000000000,BRUSIMACNPA6,167
1472917,99COTAHIST.2022BOVESPA 2022091400001472918 ...,99,COTAHIST,.2,022BOVESPA 2,022,091400001472,918,,,...,,,,,,,,,,

In [3]:
data2018b = data2018.drop(columns=[0])
data2019b = data2019.drop(columns=[0])
data2020b = data2020.drop(columns=[0])
data2021b = data2021.drop(columns=[0])
data2022b = data2022.drop(columns=[0])

In [4]:
filtrar(data2018b)
filtrar(data2019b)
filtrar(data2020b)
filtrar(data2021b)
filtrar(data2022b)

filtro de TIPREG
580156
580155
filtro de ESPECI
515700
filtro de TIPREG
779230
779229
filtro de ESPECI
700313
filtro de TIPREG
1251647
1251646
filtro de ESPECI
1110149
filtro de TIPREG
1831863
1831862
filtro de ESPECI
1612294
filtro de TIPREG
1472917
1472916
filtro de ESPECI
1294543

,TIPREG,DATA DO PREGÃO,CODBDI,CODNEG,TPMERC,NOMRES,ESPECI,MODREF,PRAZOT,PREABE,...,TOTNEG,QUATOT,VOLTOT,PREEXE,INDOPC,DATVEN,FATCOT,PTOEXE,CODISI,DISMES
28,1,20220103,02,AALR3,010,ALLIAR,ON NM,,R$,0000000001496,...,02997,000000000000601000,000000000834230700,0000000000000,0,99991231,0000001,0000000000000,BRAALRACNOR6,102
31,1,20220103,02,ABCB4,010,ABC BRASIL,PN EJ N2,,R$,0000000001582,...,07350,000000000001230500,000000001938393800,0000000000000,0,99991231,0000001,0000000000000,BRABCBACNPR4,139
32,1,20220103,02,ABEV3,010,AMBEV S/A,ON,,R$,0000000001542,...,43784,000000000023833600,000000036454098800,0000000000000,0,99991231,0000001,0000000000000,BRABEVACNOR1,125
38,1,20220103,02,AERI3,010,AERIS,ON NM,,R$,0000000000658,...,08390,000000000002606700,000000001733547500,0000000000000,0,99991231,0000001,0000000000000,BRAERIACNOR4,100
39,1,20220103,02,AESB3,010,AES BRASIL,ON NM,,R$,0000000001107,...,04571,000000000000846800,000000000921662900,0000000000000,0,99991231,0000001,0000000000000,BRAESBACNOR7,102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1472912,1,20220912,82,USIMV707,080,USIME,PNA N1,000,R$,0000000000013,...,00056,000000000000045000,000000000000588000,0000000000707,0,20221021,0000001,0000000000000,BRUSIMACNPA6,167
1472913,1,20220913,82,USIMV707,080,USIME,PNA N1,000,R$,0000000000014,...,00028,000000000000094100,000000000001426800,0000000000707,0,20221021,0000001,0000000000000,BRUSIMACNPA6,167
1472914,1,20220914,82,USIMV707,080,USIME,PNA N1,000,R$,0000000000016,...,00038,000000000000062600,000000000001201100,0000000000707,0,20221021,0000001,0000000000000,BRUSIMACNPA6,167
1472915,1,20220803,82,USIMV727,080,USIME,PNA N1,000,R$,0000000000020,...,00001,000000000000000100,000000000000002000,0000000000727,0,20221021,0000001,0000000000000,BRUSIMACNPA6,167
1472916,1,20220816,82,USIMV727,080,USIME,PNA N1,000,R$,0000000000018,...,00001,000000000000001000,000000000000018000,0000000000727,0,20221021,0000001,0000000000000,BRUSIMACNPA6,167

Juntando as tabelas

In [5]:
##Unificando a base
data = pd.concat([data2018b,data2019b,data2020b,data2021b,data2022b])
data[:5]

,TIPREG,DATA DO PREGÃO,CODBDI,CODNEG,TPMERC,NOMRES,ESPECI,MODREF,PRAZOT,PREABE,...,TOTNEG,QUATOT,VOLTOT,PREEXE,INDOPC,DATVEN,FATCOT,PTOEXE,CODISI,DISMES
1,01,20180102,02,AALR3,010,ALLIAR,ON NM,,R$,0000000001494,...,00403,000000000000094500,000000000140299100,0000000000000,0,99991231,0000001,0000000000000,BRAALRACNOR6,100
2,01,20180102,96,AALR3F,020,ALLIAR,ON NM,,R$,0000000001479,...,00007,000000000000000225,000000000000334384,0000000000000,0,99991231,0000001,0000000000000,BRAALRACNOR6,100
3,01,20180102,02,AAPL34,010,APPLE,DRN,,R$,0000000005681,...,00004,000000000000000900,000000000005074700,0000000000000,0,99991231,0000001,0000000000000,BRAAPLBDR004,123
4,01,20180102,96,AAPL34F,020,APPLE,DRN,,R$,0000000005681,...,00007,000000000000000061,000000000000363770,0000000000000,0,99991231,0000001,0000000000000,BRAAPLBDR004,123
5,01,20180102,10,ABCB2,010,ABC BRASIL,DIR PRE N2,,R$,0000000000411,...,00006,000000000000001200,000000000000497700,0000000000000,0,99991231,0000001,0000000000000,BRABCBD12PR6,128

Criando CSV

In [6]:
#Criação de csv para evitar retrabalho e economia de tempo

data.to_csv('datab3.csv',sep=',')